### ISSUE TITLE
https://pythonhosted.org/mwoauth/ docs stale (v0.2.1 shown)

### ISSUE THREAD

**Issue by bd808** [mediawiki-utilities/python-mwoauth#20]
There have been a few non-trivial API changes since v0.2.1, it's probably time to upload a new set of sphinx docs.

**Comment by jayvdb** [comment]
https://github.com/mediawiki-utilities/python-mwoauth/releases also shows v0.2.1 is the last release.

**Comment by bd808** [comment]
Apparently the later releases haven't been tagged -- https://pypi.python.org/pypi/mwoauth/0.2.7

**Comment by halfak** [comment]
Updated docs.

**Comment by halfak** [comment]
Also I updated the releases with minimal notes.
