### ISSUE TITLE
RequestToken no longer works with byte strings. 

### ISSUE THREAD

**Issue by consideRatio** [mediawiki-utilities/python-mwoauth#38]
@halfak thanks for your work on this!

Additional jupyterhub/oauthenticator integration test failures followed in using mwoauth==0.3.6: https://travis-ci.org/jupyterhub/oauthenticator/jobs/602960933

I think they relate to:
1. Type mismatch in this comparison:

https://github.com/mediawiki-utilities/python-mwoauth/blob/14687423b42f929611f517f98ef5e2efdd012618/mwoauth/functions.py#L170-L173

2. A broken expectation, where the return value from the `initiate` function's `request_token.key`, what was previously a binary blob is now a string.

---

If you would like to use these tests to debug locally, you can.

```
git clone https://github.com/jupyterhub/oauthenticator/
cd oauthenticator
pip install -r test-requirements.txt
# "pip install -e ." again on mwoauth
pytest -k mediawiki
```

**Comment by halfak** [comment]
I see.  It looks like you're setting your request_token.key to be a byte string, but in the docs (see https://github.com/mediawiki-utilities/python-mwoauth/blob/master/mwoauth/tokens.py) we define that as a string type.  It seems like byte strings were handled in the past but that was undocumented behavior.  It seems like the right solution here is to force it to be the same type for comparison.  Also, that error message looks very wrong I'll look at that too.

**Comment by halfak** [comment]
Curses to managing bytes/unicode between 2.7 and 3.x.

**Comment by halfak** [comment]
I've just uploaded https://github.com/mediawiki-utilities/python-mwoauth/pull/39  

This PR makes all of the internal use of keys and secrets unicode/strings for consistency.  With that we were able to drop all use of bytes.  I think this is the best path forward.  I suggest that you change your test to use a RequestToken with a string/unicode key & secret pair.  

What do you think?

**Comment by halfak** [comment]
Version 0.3.7 is released.  I don't think it'll bake this test pass, but it will make unicode/byte string handling consistent.

**Comment by consideRatio** [comment]
Resolved!
