### ISSUE TITLE
Release 0.3.8 or 1.0.0

### ISSUE THREAD

**Issue by consideRatio** [mediawiki-utilities/python-mwoauth#46]
Hi, I'm a maintainer of jupyterhub/oauthenticator that provides a way for the software JupyterHub to authenticate against MediaWiki and other identity providers.

`pyjwt` is a dependency for `oauthenticator` and we have maintained compatebility with version 1 and 2 for a while now because this project is also a dependency - and has in its latest release 0.3.7 pinned pyjwt to version 1.

@halfak or @FiloSottile, could you cut a release of this project again to help us out? The version could be `0.3.8` or `1.0.0` I think. Since version [0.3.7 was released 29th October 2019](https://pypi.org/project/mwoauth/#history), I [see in the commit history](https://github.com/mediawiki-utilities/python-mwoauth/commits/master) the only PRs that has been merged are #41 and #43.

### Related

- https://github.com/jupyterhub/oauthenticator/pull/506

**Comment by halfak** [comment]
Can do.  Will look into this and update.

**Comment by halfak** [comment]
OK!  I updated the dependency of PyJWT to 2.4.0.  I ran the examples and was able to auth successfully.  I pushed the updates in mwoauth 0.3.8.  It should be available in pypi shortly.
