### ISSUE TITLE
Consider cut a release for 0.4.0

### ISSUE THREAD

**Issue by Dentrax** [mediawiki-utilities/python-mwoauth#50]

**Comment by a-detiste** [comment]
please, to allow six removal

**Comment by halfak** [comment]
0.4.0 was released in Oct of last year.  See https://pypi.org/project/mwoauth/0.4.0/

**Comment by a-detiste** [comment]
Ok the Debian watcvh system does not work here https://pypi.debian.net/mwoauth

**Comment by a-detiste** [comment]
Well there's no .tgz on PyPi

**Comment by halfak** [comment]
OK I added the tgz.

**Comment by a-detiste** [comment]
Thank you
